version: "3.8"
services:
  vue-rtc:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - rtc
    ports:
      - 8080:8080
    container_name: vue-rtc
  proxy:
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - rtc
    container_name: proxy
networks:
  rtc:
    driver: bridge
